/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projaula05_livros;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Madianita Bogo
 */
public class FormBiblioteca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBiblioteca.class.getName());
    ArrayList<Livro> listaLivros = new ArrayList();
            
    /**
     * Creates new form FormBiblioteca
     */
    public FormBiblioteca() {
        initComponents();
    }
    
    public Livro buscarLivro(int codigo){
        for (Livro liv : listaLivros){
            if (liv.codigo == codigo){
                return liv; //retorno a referência do objeto encontrado
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        chkDisponivel = new javax.swing.JCheckBox();
        rbDevolver = new javax.swing.JRadioButton();
        rbEmprestar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        jButton1.setText("Inserir Livro");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Excecutar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Imprimir Todos");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Imp. por Autor");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        chkDisponivel.setSelected(true);
        chkDisponivel.setText("Disponível");

        buttonGroup1.add(rbDevolver);
        rbDevolver.setSelected(true);
        rbDevolver.setText("Devolver");

        buttonGroup1.add(rbEmprestar);
        rbEmprestar.setText("Emprestar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbDevolver)
                                    .addComponent(rbEmprestar))
                                .addGap(61, 61, 61)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkDisponivel)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(chkDisponivel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbDevolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbEmprestar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        //procurar o livro antes e se ele existir
//        String opcao = JOptionPane.showInputDialog("1 - Devolver\n2 - Realizar Empréstimo"
//                + "\n\nEscolha uma opção:");
//        
//        if (opcao.equals("1")){
//            //fazer a devolução
//        }
//        else if (opcao.equals("2")){
//            //realizar empréstimo
//        }
//        else{
//            //opção inválida
//        }

        int cod = Integer.parseInt(JOptionPane.showInputDialog("Código: "));   
        Livro livAux = buscarLivro(cod);
        if (livAux != null){ //Significa que o livro foi encontrado
            if (rbDevolver.isSelected()){
                int qtDiasAtraso = Integer.parseInt(JOptionPane.showInputDialog("Qt. de dias em atraso:"));
                taSaida.setText(livAux.devolver(qtDiasAtraso));
            }
            else{
                taSaida.setText(livAux.emprestar());
            }
        }
        else{
                taSaida.setText("Livro não encontrado!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int cod = Integer.parseInt(JOptionPane.showInputDialog("Código: "));   
        Livro livAux = buscarLivro(cod);
        
        if (livAux == null){ //Significa que código está livre
            livAux =  new Livro();
            livAux.codigo = cod;
            livAux.titulo = JOptionPane.showInputDialog("Título:");
            livAux.autor = JOptionPane.showInputDialog("Autor:");
            livAux.valorMultaDia = Double.parseDouble(JOptionPane.showInputDialog("Valor da multa por dia:"));            
            livAux.disponivel = chkDisponivel.isSelected();
            listaLivros.add(livAux);
            taSaida.setText("Livro cadastrado com sucesso!");
        }
        else{
            taSaida.setText("Já existe livro com esse código!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        taSaida.setText("Livros cadastrados:");
        for (Livro liv : listaLivros){
            taSaida.append("\n" + liv.codigo + " - " + liv.titulo + 
                    " - Livro está " + liv.verificarSituacao() + ".");
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String autor = JOptionPane.showInputDialog("Autor: ");
        taSaida.setText("Livros do autor " + autor + ":");
        for (Livro liv : listaLivros){
            if (liv.autor.equalsIgnoreCase(autor)){
                taSaida.append("\n" + liv.codigo + " - " + liv.titulo + 
                        " - Livro está " + liv.verificarSituacao() + ".");
            }
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkDisponivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbDevolver;
    private javax.swing.JRadioButton rbEmprestar;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
