
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akira
 */
public class ProdPart extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProdPart.class.getName());
    public ProdPart() {
        initComponents();
    }
    ArrayList<Participante> listaParticipantes = new ArrayList();
    
    public Participante buscarParticipante(int matricula){
        for (Participante part : listaParticipantes){
            if (part.getMatricula() == matricula){
                return part;
            }
        }
        return null;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Turmas = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        ckT1 = new javax.swing.JCheckBox();
        ckT2 = new javax.swing.JCheckBox();
        ckT3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        Turmas.add(ckT1);
        ckT1.setSelected(true);
        ckT1.setText("T01");

        Turmas.add(ckT2);
        ckT2.setText("T02");

        Turmas.add(ckT3);
        ckT3.setText("T03");

        jButton1.setText("Inserir Participante");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Imprimir por matrícula");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Imprimir Reprovados");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Analise de engajamento");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(ckT3)
                    .addComponent(ckT2)
                    .addComponent(ckT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckT1)
                    .addComponent(jButton4))
                .addGap(1, 1, 1)
                .addComponent(ckT2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckT3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Participante p;
     p = new Participante();

     p.setMatricula(Integer.parseInt(JOptionPane.showInputDialog("Matricula do Participante: ")));
     p.setNome(JOptionPane.showInputDialog("Nome do participante: "));

     if (ckT1.isSelected()){
         p.setTurma("T01");
     } else if (ckT2.isSelected()){
         p.setTurma("T02");
     } else if (ckT3.isSelected()){
         p.setTurma("T03");
     }

     p.setFreq(Integer.parseInt(JOptionPane.showInputDialog("Digite a porcentagem da frequencia do aluno")));
     p.setNota1(Double.parseDouble(JOptionPane.showInputDialog("Digite a primeira nota: ")));
     p.setNota2(Double.parseDouble(JOptionPane.showInputDialog("Digite a segunda nota: ")));
     p.setAtv(Integer.parseInt(JOptionPane.showInputDialog("Digite a Quant. de atividades do aluno")));

     Participante repetido = buscarParticipante(p.getMatricula());

     if (repetido != null){
         taSaida.setText("Está Matrícula ja existe, não foi possível realizar a ação");
     } else {
         listaParticipantes.add(p);
         taSaida.setText("Participante Inserido \n");
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int mat = Integer.parseInt(JOptionPane.showInputDialog("Qual a matricula que deseja procurar: "));
        Participante p = buscarParticipante(mat);
        if (p == null){
           taSaida.setText("Está matricula não foi encontrada ou é inexistente, não foi possível realizar a ação");
        } else {
            taSaida.setText(p.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String turma = JOptionPane.showInputDialog("Qual a turma que deseja ver? ");
        for (Participante p: listaParticipantes){
            if ((p.situacao().equals("Reprovado por frequência") || p.situacao().equals("Reprovado por Nota")) && p.getTurma().equals(turma)){
                taSaida.setText("");
                taSaida.append("\n" + p.getNome() + " Situação: " + p.situacao() +"\n");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int soma = 0, cont = 0;        
        for( Participante p: listaParticipantes){
            if (p.situacao().equals("Aprovado!")){
                soma += p.getAtv();
                cont++;
            }
        }
        if (cont > 0){
            double media = soma / cont;
            taSaida.setText("A media de produtividade dos aprovados é: " + media);
        } else {
            taSaida.setText("Não há participantes aprovados, não foi possivel realizar a ação.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProdPart().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Turmas;
    private javax.swing.JCheckBox ckT1;
    private javax.swing.JCheckBox ckT2;
    private javax.swing.JCheckBox ckT3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
